### ISSUE TITLE
iPhoneX8 goes down a few pixels down.

### ISSUE THREAD

**Issue by eastswift** [aFrogleap/SimpleImageViewer#12] opened 2017-12-27 22:38 UTC
IPhone 8 goes down a few pixels down.
Other devices have no problem.

It seems to be a problem of iPhone X's height, but I do not know the solution.

**Comment by LcTwisk** [comment] 2017-12-28 06:48
Thanks for reporting. Let’s see if I can reproduce the issue 👍🏼

**Comment by LcTwisk** [comment] 2017-12-29 14:04
@eastswift can you check if the issue is fixed in the latest version (1.1.1)?

**Comment by eastswift** [comment] 2017-12-30 15:10
It works well. It's cool.

**Closed** 2017-12-30 17:46 UTC
